Drop the dependency on python-trololio (in favor of asyncio)
On Fedora 38, using python 3.11 'trololio' is broken and no updates
have been made to it for almost 10 years. Time to use 'raw' asyncio.

Details

trololio feature two issues.

1) Trololio depend on deprecated `imp` module:

```
>>> from imp import find_module, load_module
<stdin>:1: DeprecationWarning: the imp module is deprecated in favour of
importlib and slated for removal in Python 3.12; see the module's
documentation for alternative uses
```

2) Trololio's embedded asyncio module fails. So trololio methods are
never defined. For example:

```
$ cat trolo-smoke.py
from trololio import asyncio, coroutine
@coroutine
def coro():
   yield From(asyncio.sleep(1))

$ python trolo-smoke.py
AttributeError: module 'trololio.asyncio' has no attribute 'coroutine'.
Did you mean: 'coroutines'?
```

The same issue can be seen in the `pagure-ev` logs

```
pagure_stream_server.py[192893]:   File
"/usr/libexec/pagure-ev/pagure_stream_server.py", line 140, in <module>
pagure_stream_server.py[192893]:     @asyncio.coroutine
pagure_stream_server.py[192893]:      ^^^^^^^^^^^^^^^^^
pagure_stream_server.py[192893]: AttributeError: module 'asyncio' has no
attribute 'coroutine'. Did you mean: 'coroutines'?
```

Signed-off-by: Dominik Wombacher <dominik@wombacher.cc>