fix: strip() without testing if var is not None
Usage of 'strip()' without testing if var exist / is not None caused "AttributeError: 'NoneType' object has no attribute 'strip'" in various tests