Make the CSP header be bytes not unicode
Header names must be byte string not unicode string, so we need
to make sure our CSP header complies with that.

Otherwise we run into:
  Apache returning a 500 error:
    TypeError: expected byte string object for header name,
    value of type unicode found

Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>